version: '3.1'
services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - ENABLE_CORS=true
      - ENABLE_LOGGER=true
      - LOGGER_PRETTY_PRINT=true
    volumes:
      - .:/app
    command: npm run dev
  db:
    image: mongo:5.0.0
    expose:
      - 27017
    command: --noscripting
